<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for django-command-exception</title>
  </head>
  <body>
    <h1>Links for django-command-exception</h1>
<a href="https://files.pythonhosted.org/packages/98/33/4896829920fc6261a61004788f3f16a2aac1967f20a707bdc702f9a51f12/django_command_exception-1.0.0.tar.gz#sha256=055673638675d625b18a408ae547d20e948a438f45e3476f7f1125f796778143" >django_command_exception-1.0.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/d1/72/2fc5b08288f0fbdf8c5a030b97f696c8972a69eb0e25faa0d86595e50f03/django_command_exception-1.0.1.tar.gz#sha256=6d4f5e3b16b516cedcd4f90dfc84bdc5bf481253f0bcc97ca3ebacc885ffe6f1" >django_command_exception-1.0.1.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/ac/51/c5296b4dac2478b778987392e892ebaa77dd035dfa838cf4aeaf92e45a7f/django_command_exception-1.0.2.tar.gz#sha256=c4f0bdc40ac60fc64b0ea0b5122e0af5119791de4c3929a2a4619fcafbffcf52" >django_command_exception-1.0.2.tar.gz</a><br />
</body>
</html>
<!--SERIAL 24219920-->