<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for showexception</title>
  </head>
  <body>
    <h1>Links for showexception</h1>
<a href="https://files.pythonhosted.org/packages/32/ef/70e9e13fda7d3d5800e925b98f32d82ec3e5ffa11fd83c508f2ad89b5e17/showexception-0.1.0-py3-none-any.whl#sha256=300586e932457d1a5c139128cc93e99042f97e3536efd3d7acb175dc3fc8614b" data-requires-python="&gt;=3.9" data-dist-info-metadata="sha256=120816379698c772e6dfb3e8f21837775f8002b794231e93c550cf8815a089e7" data-core-metadata="sha256=120816379698c772e6dfb3e8f21837775f8002b794231e93c550cf8815a089e7">showexception-0.1.0-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/a8/52/9865144d74f650ea84b99af320024519bc6c67903ed18a002b28b114f567/showexception-0.1.0.tar.gz#sha256=083fd136853813543143c56c2d661acd91f9d0c7ed7977d067b3071f415bc9e7" data-requires-python="&gt;=3.9" >showexception-0.1.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/9f/5f/1365e2e4f4501fc2156aae565c9daf70972668ab6214b84f6219889962e4/showexception-0.1.1-py3-none-any.whl#sha256=a76402f3f91f80f12d398e6b937a53e5c1dbe4834ecfa53b56386ef7b0cf4316" data-requires-python="&gt;=3.9" data-dist-info-metadata="sha256=3da5f338f833fd7c13614121759bc345f6d6f3214d7376d7ffade347dc3e36c0" data-core-metadata="sha256=3da5f338f833fd7c13614121759bc345f6d6f3214d7376d7ffade347dc3e36c0">showexception-0.1.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/6b/fb/5a0a45c72fbb33b793265b8308a3b36b9dca5ce9e3ca76d3b90fc6133764/showexception-0.1.1.tar.gz#sha256=389672a1b10764b95e1a2fa6e2c3336d14ef2cad30225f81b8aefdb75fbefdec" data-requires-python="&gt;=3.9" >showexception-0.1.1.tar.gz</a><br />
</body>
</html>
<!--SERIAL 24312293-->